version: '2'
services:
    scheduler-postgresql:
        image: postgres:18.4
        # volumes:
        #     - ~/volumes/jhipster/scheduler/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=scheduler
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=scheduler
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "127.0.0.1:${POSTGRES_PORT}:5432"
