version: '3.3'
services:
    scheduler-app:
        image: xmonline/xm-ms-scheduler:${IMAGE_TAG:-latest}
        networks:
            - xm2
        env_file:
            - ./env/scheduler-app.env
        secrets:
            - source: SPRING_DATASOURCE_PASSWORD
              target: SPRING_DATASOURCE_PASSWORD
            - source: SPRING_DATASOURCE_URL
              target: SPRING_DATASOURCE_URL
            - source: SPRING_DATASOURCE_USERNAME
              target: SPRING_DATASOURCE_USERNAME
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: scheduler
                syslog-facility: local7

secrets:
    SPRING_DATASOURCE_PASSWORD:
        external: true
    SPRING_DATASOURCE_URL:
        external: true
    SPRING_DATASOURCE_USERNAME:
        external: true

networks:
    xm2:
        driver: overlay
